sebsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chat/', include('tables.urls')),
    url(r'^', include('users.urls')),


]

tables/urls.py
# chat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^inbox/$', views.inbox, name='inbox'),
    url(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),
    url(r'^private/(?P<room_name>[^/]+)/$', views.private_room, name='private_room'),
    url(r'^ajax/key_gen/$', views.key_gen, name='key_gen'),
    url(r'^ajax/encrypt/$', views.encrypt, name='encrypt'),
    url(r'^ajax/decrypt/$', views.decrypt, name='decrypt'),
    url(r'^ajax/time_series/$', views.get_time_series, name='time_series'),
    url(r'^ajax/leader_board/$', views.get_leader_board, name='leader board'),

]

users/urls.py
from django.conf.urls import url, include
from . import views


app_name = "users"

urlpatterns = [
    url(r'^signup/', views.signup_view, name='signup'),
    url(r'^login/', views.login_view, name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'', views.index, name='home'),
    ]

tables/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User
from hashlib import md5


class Room(models.Model):
    title = models.CharField(max_length=255)
    permanent = models.BooleanField(default=0)

    def __str__(self):
        return self.title


class Room_Population(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    population = models.PositiveIntegerField(default=0)
    time = models.DateTimeField(default=now, blank=True)

    def __str__(self):
        return '{}:{}={}'.format(self.time, self.room, self.population)


class Private_Message(models.Model):
    from_a = models.ForeignKey(User, on_delete=models.CASCADE, related_name='from_a')
    to_b = models.ForeignKey(User, on_delete=models.CASCADE, related_name='to_b')
    message =  models.TextField(blank=False)
    time = models.DateTimeField(default=now, blank=True)
    read = models.BooleanField(default=0)

    def __str__(self):
        return '{}:{}={}@{}'.format(self.from_a, self.to_b, self.message, self.time)

class Private_Room(models.Model):
    link = models.CharField(max_length=255, unique=True)
    user_one = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_one')
    user_two = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_two')
    time = models.DateTimeField(default=now, blank=True)

    def save(self, **kwargs):
        bytes_string = bytes('{}{}'.format(self.user_one, self.user_two), 'utf-8')
        self.link = md5(bytes_string).hexdigest()
        super(Private_Room, self).save()

    def __str__(self):
        return '{}:{}@{}'.format(self.user_one, self.user_two, self.time)

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User

class UserCreationForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')

tables/views.py
from django.shortcuts import render
from django.utils.safestring import mark_safe
import json
from django.http import JsonResponse
from Crypto.PublicKey import RSA
from Crypto import Random
from .models import Room, Room_Population, Private_Message, Private_Room
from hashlib import md5
from django.http import HttpResponseNotFound
from django.contrib.auth.models import User



def index(request):
    return render(request, 'tables/index.html', {})


def room(request, room_name):
    return render(request, 'tables/room.html', {
        'room_name_json': mark_safe(json.dumps(room_name)),
    })

def private_room(request, room_name):
    # hash = md5(b'{}{}'.format(request.user_one, request.user_two)).hexdigest()
    pr = Private_Room.objects.get(link=room_name)
    print("trying to access private room")
    other = [user for user in [pr.user_one, pr.user_two] if user!= request.user]

    if request.user in [pr.user_one, pr.user_two]:
        return render(request, 'tables/private_room.html', {
            'room_name_json': mark_safe(json.dumps(room_name)), 'partner': other[0].username,
        })
    else:
        return HttpResponseNotFound('<h1>No Page Here</h1>')

def inbox(request):
    username = None
    if request.user.is_authenticated:
        user = request.user
        messages = Private_Message.objects.filter(to_b=user).order_by('-time')
    return render(request, 'tables/inbox.html', {'messages':messages})



def key_gen(request):
    if request.method == 'POST':
        print(request)
        random_generator = Random.new().read
        key = RSA.generate(1024, random_generator)
        data = {
            'n': hex(key.n),
            'e': hex(key.e),
            'd': hex(key.d),
            'p': hex(key.p),
            'q': hex(key.q),
            'u': hex(key.u),
        }
        return JsonResponse(data)
    else:
        print("key_gen no work")
        return JsonResponse({})



def decrypt(request):
    encrypted_message = request.POST.get('encrypted_message', None)
    print(encrypted_message)
    encrypted_message = [int(i) for i in encrypted_message.split(',')]
    print(encrypted_message)
    n = int(request.POST.get('n', None), 16)
    e = int(request.POST.get('e', None), 16)
    d = int(request.POST.get('d', None), 16)
    p = int(request.POST.get('p', None), 16)
    q = int(request.POST.get('q', None), 16)
    u = int(request.POST.get('u', None), 16)
    priv_key = RSA.construct((n, e, d, p, q, u))
    print("#####")
    decrypted_message = priv_key.decrypt(bytes(encrypted_message))
    print("#######", decrypted_message, "#######")
    data = {
        'decrypted_message': str(decrypted_message, 'utf-8'),
    }
    return JsonResponse(data)


def encrypt(request):
    message = bytes(request.POST.get('message', None), 'utf-8')
    n = int(request.POST.get('n', None), 16)
    e = int(request.POST.get('e', None), 16)
    pub_key = RSA.construct((n, e))
    encrypted_message = pub_key.encrypt(message, 32)[0]
    encrypted_message = list(encrypted_message)
    data = {
        'encrypted_message': encrypted_message,
    }

    return JsonResponse(data)

def get_time_series(request):
    room_title = request.GET.get('label', None)
    print("#######",  request.GET, "#######")
    room = Room.objects.get(title=room_title)
    d2 = {}
    d2["room"]=room.title
    room_pop_data = Room_Population.objects.filter(room=room).order_by('time')
    d2["data"] = [{"x":item.time.timestamp(), "y":item.population} for item in room_pop_data]
    data = d2
    print(d2)
    return JsonResponse(data)

def get_leader_board(request):
    label_data_list = []
    for room in Room.objects.all():
        try:
            population = Room_Population.objects.filter(room=room).latest('time').population
        except:
            population = 0
        d = {}
        d["label"]=room.title
        d["data"]= population
        label_data_list.append(d)

    label_data_list = sorted(label_data_list, key=lambda k: k['data'], reverse=True)
    labels = [i['label'] for i in label_data_list]
    data = [i['data'] for i in label_data_list]
    d = {
        'labels': labels,
        'data': data,
        # 'time_series':room_pop_time,
        }
    return JsonResponse(d)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


def index(request):
    return render(request, 'users/home.html')

def signup_view(request):
    print(request.method)
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('/chat/')
    else:
        form = UserCreationForm()
    return render(request, 'users/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/chat/')
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
    return redirect('/chat/')

tables/templates/tables/dashboard.html
<!doctype html>
<html>
	<head>
    	<title>DjangoCity Dashboard</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	</head>
	<body>
    	<div class="container">
        	<table class="table">
            	<thead>
                	<tr>
                    	<th>Voter</th>
                    	<th>Housing</th>
                    	<th>Parks</th>
                    	<th>Schools</th>
                    	<th>Public Safety</th>
                	</tr>
            	</thead>
            	<tbody>
                	{% for voter in voters %}
                	<tr>
                    	<td>{{  voter }}</td>
                    	<td>Yes: <span class="js-{{ voter.id }}-housing-yes">0</span> No: <span class="js-{{ voter.id }}-housing-no">0</span></td>
                    	<td>Yes: <span class="js-{{ voter.id }}-parks-yes">0</span> No: <span class="js-{{ voter.id }}-parks-no">0</span></td>
                    	<td>Yes: <span class="js-{{ voter.id }}-schools-yes">0</span> No: <span class="js-{{ voter.id }}-schools-no">0</span></td>
                    	<td>Yes: <span class="js-{{ voter.id }}-safety-yes">0</span> No: <span class="js-{{ voter.id }}-safety-no">0</span></td>
                	</tr>
                	{% endfor %}
            	</tbody>
        	</table>
    	</div>
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        <script>
            $(document).ready(function() {
               socket = new WebSocket("ws://" + window.location.host);
               socket.onmessage = function(e) {
                   var data = JSON.parse(e.data);
                   for (var voter in data) {
                       for (var category in data[voter]) {
                           $(".js-" + voter + "-" + category + "-yes").text(data[voter][category]['yes']);
                           $(".js-" + voter + "-" + category + "-no").text(data[voter][category]['no']);
                       }
                   }
               }
            });
        </script>
	</body>
</html>

tables/templates/tables/example.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8"/>
<title>Chat Room</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<style>
body {margin:0;}

.navbar {
    padding-left: 55px;
    background-color: orange;
    overflow: hidden;
    position: fixed;
    bottom: 0;
    width: 100%;
}

#messages_container {
  border: solid;
  padding: 5px;
  height: 600px;
  overflow: scroll;
}

.navbar a {
  float: left;
  display: block;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.navbar a:hover {
  background: #f1f1f1;
  color: black;
}

.navbar a.active {
  background-color: #4CAF50;
  color: white;
}

.main {
  padding: 16px;
  margin-bottom: 30px;
}

#chat-message-input{
  width:20%;
}

#chat-message-input2{
  width:50%;
}
#chat-message-submit{
  background-color: light-green;
}
</style>
</head>
<body>

<div class="navbar">
  <input id="chat-message-input" type="text" size="100" value="username"/>
  <input id="chat-message-input2" type="text" size="100" value="message" />
  <input id="chat-message-submit" type="button" value="Send"/>
  <label class="checkbox-inline"><input type="radio" value="" name="logo"> <span class="glyphicon glyphicon-print"></span></label>
  <label class="checkbox-inline"><input type="radio" value="" name="logo"> <span class="glyphicon glyphicon-print"></span></label>
  <label class="checkbox-inline"><input type="radio" value="" name="logo"> <span class="glyphicon glyphicon-print"></span></label>

</div>

<div class="container">
  <h1 id="title"></h1>
</div>

<div class="container" id="messages_container">

  <div class="media" id="message0">
    <div class="media-left">
      <span class="glyphicon glyphicon-print"></span>
    </div>
    <div class="media-body">
      <h4 class="media-heading" id="username">John Doe</h4>
      <p id="message">Lorem ipsum...</p>
    </div>
  </div>
</div>



</body>

<script>
    var roomName = {{ room_name_json }};
    document.getElementById("title").innerHTML = roomName;





    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + roomName + '/');

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var new_message_1 =  '<div class="media"><div class="media-left"><span class="glyphicon glyphicon-print"></span></div>';
        var new_message_2 =  '<div class="media-body"><h4 class="media-heading" id="username_">';
        var username = data['message'];
        var new_message_3 =  '';
        var new_message_4 =  "</h4><p>";
        var message = data['message2'];
        var new_message_5 =  '</p></div>';
        var new_message = new_message_1 + new_message_2 + username + new_message_3 + new_message_4 + message + new_message_5
        $("#messages_container").append(new_message);
        updateScroll();

    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input2').focus();
    document.querySelector('#chat-message-input2').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        var messageInputDom2 = document.querySelector('#chat-message-input2');
        var message2 = messageInputDom2.value;
        chatSocket.send(JSON.stringify({
            'message': message,
            'message2': message2
        }));

        messageInputDom2.value = '';
    };

    function updateScroll(){
      var out = document.getElementById("messages_container");

      var isScrolledToBottom = out.scrollHeight - out.clientHeight <= out.scrollTop + 100;
      console.log(out.scrollHeight - out.clientHeight,  out.scrollTop + 100);
      if(isScrolledToBottom)
          out.scrollTop = out.scrollHeight - out.clientHeight;
      }
</script>
</html>

tables/templates/tables/inbox.html
{% extends "users/base.html" %} {% block content %}

<div class='container'>
    <h2><span id="title">Your Inbox</span> <a href="../" class="pull-right" id="inbox">Dash</a></h2>
    <br/>
    <br/>

</div>

<div class="container" id="tools">
  <input type="button" class="tool_button" id="compose_button" value="Compose"/>
  <input type="button" class="tool_button" id="priv_chat_button" value="Private Chat"/>
  <input type="button" class="tool_button" id="delete_all_button" value="Delete All"/>
  <div id="compose_message">
    <input id="new_to_b" type="text" size="10" placeholder="User"/>
    <input id="new_message" type="text" size="100" value="" placeholder="Message" />
    <input id="new_submit" type="button" value="Send"/>
  </div>
  <div id="priv_chat_request">
    <input id="priv_chat_to_b" type="text" size="10" placeholder="User"/>
    <input id="priv_chat_submit" type="button" value="Send"/>
  </div>
</div>
<div class="container" id="messages_container">
  {% for message in messages %}
  {% if not message.read %}
  <div class="media">
    <hr>
    <div class="media-left media-top">
      <a href="#" class="read_button"><span class="glyphicon glyphicon-trash"></span></a><a class="private_chat_request_button"><span class="glyphicon glyphicon-comment"></span></a>
    </div>
    <div class="media-body">
      <h4 class="media-heading" id="from_a">{{ message.from_a }}</h4>
      <p>{{ message.message }} <small>{{ message.time }}</small></p><p id="message_id"> {{ message.id }} </p>
      <input id="reply-message" type="text" size="100" placeholder="Reply" />
      <input id="reply-submit" type="button" value="Send"/>
    </div>
  </div>
  {% endif %}
  {% endfor messages %}


</div>

<br></br>
<br></br>
<script>
var chatSocket = new WebSocket(
    'ws://' + window.location.host +
    '/ws/inbox/');


chatSocket.onmessage = function(e) {
  var data = JSON.parse(e.data);
  console.log(data);
  if (data.content == 'private_chat_request'){
    var n1 = '<div class="media"><hr><div class="media-left media-top"><a href="#" class="remove_button"><span class="glyphicon glyphicon-trash"></span></a></div><div class="media-body"><h4 class="media-heading" id="from_a">'
    var n2 = data.from_a + '</h4><a class="priv_link" href="../private/' + data.link + '/">' + data.link + '</a> <small>' + data.time + '</small></p><p id="message_id">' + data.id + '</p>'
    var n3 = '</div></div>'
    var new_message = n1 + n2 + n3;
    $("#messages_container").prepend(new_message);
  }
  if (data.content == 'visited_private_room'){
    var n1 = '<div class="media"><hr><div class="media-left media-top"><a href="#" class="read_button"><span class="glyphicon glyphicon-trash"></span></a></div><div class="media-body"><h4 class="media-heading" id="from_a">'
    var n2 = data.from_a + ' joined</h4><a class="priv_link" href="../private/' + data.link + '/">' + data.link + '</a> <small>' + data.time + '</small></p>'
    var n3 = '</div></div>'
    var new_message = n1 + n2 + n3;
    $("#messages_container").prepend(new_message);
  }
  if (data.content == 'inbox_message'){
    var n1 = '<div class="media"><hr><div class="media-left media-top"><a href="#" class="read_button"><span class="glyphicon glyphicon-trash"></span><a href="#" class="read_button"></a><a class="private_chat_request_button"><span class="glyphicon glyphicon-comment"></span></a></div><div class="media-body"><h4 class="media-heading" id="from_a">'
    var n2 = data.from_a + '</h4><p>' + data.message + ' <small>' + data.time + '</small></p><p id="message_id">' + data.id + '</p>'
    var n3 = '<input id="reply-message" type="text" size="100" placeholder="Reply" /><input id="reply-submit" type="button" value="Send"/></div></div>'
    var new_message = n1 + n2 + n3;
    $("#messages_container").prepend(new_message);
  }
}

chatSocket.onclose = function(e) {
    console.error('Chat socket closed unexpectedly');
};


$("#messages_container").on("click", "#reply-submit", function() {
  var to_b = $(this).siblings("#from_a").html();
  console.log(to_b);
  var message = $(this).siblings("#reply-message").val();
  console.log(message);

  chatSocket.send(JSON.stringify({
      'content': 'send_message',
      'from_a': '{{ user.username }}',
      'to_b': to_b,
      'message': message,
  }));

  $(this).siblings("#reply-message").val('');
})


$("#messages_container").on("click", ".priv_link", function() {
  var to_b = $(this).siblings("#from_a").html();
  var link = $(this).html();
  console.log(to_b);

  chatSocket.send(JSON.stringify({
      'content': 'visted_private_room',
      'from_a': '{{ user.username }}',
      'to_b': to_b,
      'link': link,
    }));

});




$("#messages_container").on("click", ".read_button", function() {
  var id = $(this).parents("div.media").children("div.media-body").children("#message_id").html();
  chatSocket.send(JSON.stringify({
      'content': 'read_message',
      'id': id,
  }));
  $(this).parents("div.media").remove();
});

$("#delete_all_button").click(function(){
  var to_delete = $(".read_button");
  console.log(to_delete);
  for (i=0; i<to_delete.length; i++){
    var id = $(to_delete[i]).parents("div.media").children("div.media-body").children("#message_id").html();
    console.log(id);
    chatSocket.send(JSON.stringify({
        'content': 'read_message',
        'id': id,
    }));
    $(to_delete[i]).parents("div.media").remove();
  }
});

$("#compose_button").click(function(){
  $("#compose_message").toggle();
});

$("#priv_chat_button").click(function(){
  $("#priv_chat_request").toggle();
});

$("#new_submit").click(function(){
  var to_b = $("#new_to_b").val();
  console.log(to_b);
  var message = $("#new_message").val();
  console.log(message);

  chatSocket.send(JSON.stringify({
      'content': 'send_message',
      'from_a': '{{ user.username }}',
      'to_b': to_b,
      'message': message,
    }));

    $("#new_to_b").val('');
    $("#new_message").val('');
    $("#compose_message").toggle();
});


$("#priv_chat_submit").click(function(){
  var to_b = $("#priv_chat_to_b").val();
  console.log(to_b);

  chatSocket.send(JSON.stringify({
      'content': 'create_private_room',
      'from_a': '{{ user.username }}',
      'to_b': to_b,
    }));

    $("#priv_to_b").val('');
    $("#priv_chat_request").toggle();
});

$("#messages_container").on("click", ".private_chat_request_button", function() {
  var to_b = $(this).parents(".media").children(".media-body").children(".media-heading").html()
  console.log(to_b);

  chatSocket.send(JSON.stringify({
      'content': 'create_private_room',
      'from_a': '{{ user.username }}',
      'to_b': to_b,
    }));

    $("#priv_to_b").val('');
    // $("#priv_chat_request").toggle();
});



</script>

{% endblock content %}

users/templates/users/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"></script>
<style>

body{
  background: linear-gradient(grey, black);

}


.encryption_selection{
  padding-left: 7%;
  display: inline;
  }

.encryption_selection p{
  /* position: absolute; */
  left: 10%;
  display: inline;
}

.key-pair{
  position: absolute;
  right: 10%;
  display: inline;
}

.tool_button{
  background: orange;
}

#inbox{
  background: orange;
  padding: 5px;
  color: black;
}

#compose_message{
  display: none;
  margin: 5px;
}

#priv_chat_request{
  display: none;
  margin: 5px;
}

#tools{
  background: orange;
  /* font-size: 10px; */
  color: black;
  border: solid;
  border-bottom: 0px;
}

#message_id {
  display: none;
}

.chart-container{
  width: 400px;
  height: 400px;
  color: white;
}

.line-container{
  width: 400px;
  height: 400px;
  color: white;
}

#myLeaderBoard {
  color:orange;
  font-size: 20px;
}

#myLeaderBoard a{
  color:orange;
  font-size:15px;
}
#title{
  /* color:white; */
  background: orange;
  padding: 5px;
}
  #messages_container {
    border: solid;
    padding: 5px;
    height: 80vh;
    overflow-x:scroll;
    overflow-y:scroll;
    background: linear-gradient(lightgrey, orange);
  }

.message{
   float:left;
}

  .navbar {
      padding-left: 55px;
      margin-bottom: 0px;
      border-radius: 0px;
      border: 10px solid transparent;
      background-color: orange;
      overflow: hidden;
      position: fixed;
      bottom: 0;
      width: 100%;

  }

  .btn {
      color: black; /* Add a text color */
      padding: 14px 28px; /* Add some padding */
      cursor: pointer; /* Add a pointer cursor on mouse-over */
  }

  .success {background-color: orange;} /* Green */
  .success:hover {background-color: #46a049;}

  .info {background-color: orange} /* Blue */
  .info:hover {background: #0b7dda;}

  .warning {background-color: orange;} /* Orange */
  .warning:hover {background: #e68a00;}

  .danger {background-color: orange;} /* Red */
  .danger:hover {background: #da190b;}

  .default {background-color: orange;} /* Gray */
  .default:hover {background: #ddd;}


#chat-message-input{
  width:10%;
}

#chat-message-input2{
  width:80%;
}

#chat-message-submit{
  background-color: light-green;
}

</style>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

users/templates/users/home.html
{% extends "users/base.html" %} {% block content %}

<div class='container'>
    <h1><span id="title">Encrypted Chat Rooms</span></h1>
    <br/>
    <br/>

    <a href="{% url 'users:login' %}"><button class="btn success">Login</button></a>
    <a href="{% url 'users:signup' %}"><button class="btn info">Signup</button></a>
    <a href="{% url 'users:signup' %}"><button class="btn danger">Info</button></a>



  <h3><span id="title">Popular rooms ATM</span></h3>

  <li><a href="">1</a></li>
  <li><a href="">1</a></li>
  <li><a href="">1</a></li>
  <li><a href="">1</a></li>
  <li><a href="">1</a></li>

  </br>
  <br>
  <br>

</div>
<script>
    document.querySelector('#room-name-input').focus();
    document.querySelector('#room-name-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#room-name-submit').click();
        }
    };

    document.querySelector('#room-name-submit').onclick = function(e) {
        var roomName = document.querySelector('#room-name-input').value;
        window.location.pathname = '/chat/' + roomName + '/';
    };
</script>

{% endblock content %}

users/templates/users/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br/>
    <input id="room-name-input" type="text" size="100"/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>
</body>
<script>
    document.querySelector('#room-name-input').focus();
    document.querySelector('#room-name-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#room-name-submit').click();
        }
    };

    document.querySelector('#room-name-submit').onclick = function(e) {
        var roomName = document.querySelector('#room-name-input').value;
        window.location.pathname = '/chat/' + roomName + '/';
    };
</script>
</html>

users/templates/users/login.html
{% extends "users/base.html" %} {% block content %}


<div class="container">

	<h2 class="clear_title">Login</h2>
	<div>

	<div class="container">
			<form method="POST" action="{% url 'users:login' %}" style="color:grey">
				{% csrf_token %} {{ form|linebreaks }}
				<input class="btn btn-primary" type="submit" value="Log in" />

			</form>
			<a href='{% url 'users:signup' %}'>Sign up</a>
		</div>
	<br></br>
</div>
</div>

{% endblock %}

users/templates/users/signup.html
{% extends "users/base.html" %} {% block content %}


<div class="container">

	<h2 class="clear_title">Sign up</h2>
	<div>

	<div class="container">
			<form method="POST" action="{% url 'users:signup' %}" style="color:grey">
				{% csrf_token %} {{ form|linebreaks }}
				<input class="btn btn-primary" type="submit" value="Log in" />

			</form>
			<!-- <a href='{% url 'users:signup' %}'>Sign up</a> -->
		</div>
	<br></br>
</div>
</div>

{% endblock %}